[package]
name = "adwbar"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5", features = ["derive"] }
gtk4-layer-shell = "0.7.0"
niri-ipc = "25.8.0"
relm4 = { version = "0.10", features = ["libadwaita", "gnome_48"] }
zbus = "5.12.0"
